apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "nginx-example"
  labels:
    app.kubernetes.io/name: "nginx-example"
spec:
  descriptor:
    links:
      - description: 'Open Nginx Example'
        url: "http://example-nginx"
