---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: nginx-example
spec:
  title: Nginx Example
  icon: https://cdn.auth0.com/blog/nginx-plus/nginx-logo.png
  ports:
    - serviceName: "example-nginx"
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://example-nginx"
